version: "3.8"

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:jammy
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    network_mode: service:postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
